#!/usr/bin/env bash

# Copyright (C) 2015 Yann E. MORIN <yann.morin.1998@free.fr>
# Copyright (C) 2016 Samuel Martin <s.martin49@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

# This script scans $(HOST_DIR)/{bin,sbin} for all ELF files, and checks
# they have an RPATH to $(HOST_DIR)/usr/lib if they need libraries from
# there.

source "${0%/*}/shell/source.sh"

source.load_module readelf

main() {
    local pkg="${1}"
    local hostdir="${2}"
    local file ret

    # Remove duplicate and trailing '/' for proper match
    hostdir="$(sed -r -e 's:/+:/:g; s:/$::;' <<<"${hostdir}")"

    ret=0
    while read file; do
        READELF=readelf readelf.needs_rpath "${file}" "${hostdir}" || continue
        READELF=readelf readelf.has_rpath "${file}" "${hostdir}" && continue
        if [ ${ret} -eq 0 ]; then
            ret=1
            printf "***\n"
            printf \
                "*** ERROR: package %s installs executables without proper RPATH:\n" \
                "${pkg}"
        fi
        printf "***   %s\n" "${file}"
    done < <(find "${hostdir}"/{,usr/}{bin,sbin} -type f -print 2>/dev/null |
              readelf.filter_elf_executable)

    return ${ret}
}

main "${@}"
